zone 0.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone 56.168.192.in-addr.arpa/IN: loaded serial 2014080600
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone mylab.local/IN: loaded serial 2014080600
zone localhost.localdomain/IN: loaded serial 0
zone localhost/IN: loaded serial 0
managed-keys-zone ./IN: loaded serial 0
running
zone 56.168.192.in-addr.arpa/IN: sending notifies (serial 2014080600)
zone mylab.local/IN: sending notifies (serial 2014080600)
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:f::1#53
error (network unreachable) resolving 'ns.isc.afilias-nst.info/A/IN': 2001:500:41::1#53
error (network unreachable) resolving 'ns.isc.afilias-nst.info/A/IN': 2001:500:49::1#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2001:7fd::1#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2001:7fd::1#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2001:503:a83e::2:30#53
error (network unreachable) resolving 'ns.isc.afilias-nst.info/A/IN': 2a01:8840:9::1#53
error (network unreachable) resolving 'ns.isc.afilias-nst.info/A/IN': 2a01:8840:8::1#53
error (network unreachable) resolving 'ns2.isc.ultradns.net/A/IN': 2610:a1:1014::e8#53
error (network unreachable) resolving 'pdns196.ultradns.org/A/IN': 2001:500:48::1#53
error (network unreachable) resolving 'pdns196.ultradns.org/AAAA/IN': 2001:500:48::1#53
error (network unreachable) resolving 'pdns196.ultradns.org/A/IN': 2001:500:e::1#53
error (network unreachable) resolving 'pdns196.ultradns.org/AAAA/IN': 2001:500:e::1#53
error (network unreachable) resolving 'pdns196.ultradns.biz/A/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving 'pdns196.ultradns.biz/AAAA/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving 'pdns196.ultradns.com/AAAA/IN': 2610:a1:1016::e8#53
error (network unreachable) resolving 'pdns196.ultradns.com/AAAA/IN': 2001:502:f3ff::e8#53
error (network unreachable) resolving 'pdns196.ultradns.com/A/IN': 2001:503:ba3e::2:30#53
error (network unreachable) resolving 'pdns196.ultradns.com/A/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving './NS/IN': 2001:503:ba3e::2:30#53
error (network unreachable) resolving './NS/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving 'pdns196.ultradns.com/A/IN': 2001:502:4612::e8#53
error (network unreachable) resolving 'dns02/A/IN': 2001:500:2f::f#53
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.56.11#53
no longer listening on ::1#53
exiting
zone 0.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone 56.168.192.in-addr.arpa/IN: loaded serial 2014080600
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone mylab.local/IN: loaded serial 2014080600
zone localhost.localdomain/IN: loaded serial 0
zone localhost/IN: loaded serial 0
managed-keys-zone ./IN: loaded serial 3
running
zone 56.168.192.in-addr.arpa/IN: sending notifies (serial 2014080600)
zone mylab.local/IN: sending notifies (serial 2014080600)
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.56.11#53
no longer listening on ::1#53
exiting
zone 0.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone 56.168.192.in-addr.arpa/IN: loaded serial 2014080600
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone mylab.local/IN: loaded serial 2014080600
zone localhost.localdomain/IN: loaded serial 0
zone localhost/IN: loaded serial 0
managed-keys-zone ./IN: loaded serial 3
running
zone 56.168.192.in-addr.arpa/IN: sending notifies (serial 2014080600)
zone mylab.local/IN: sending notifies (serial 2014080600)
error (network unreachable) resolving './DNSKEY/IN': 2001:dc3::35#53
error (network unreachable) resolving 'www.bluecatnetworks.com/A/IN': 2001:500:18::254#53
error (network unreachable) resolving 'aus2.akam.net/A/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving 'aus2.akam.net/AAAA/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving 'a.service.afiliasdns.info/AAAA/IN': 2001:500:1a::1#53
error (network unreachable) resolving 'dns-01.ns.aol.com/A/IN': 2001:503:a83e::2:30#53
error (network unreachable) resolving 'dns-01.ns.aol.com/AAAA/IN': 2001:503:a83e::2:30#53
error (network unreachable) resolving 'dns-02.ns.aol.com/A/IN': 2001:503:231d::2:30#53
error (network unreachable) resolving 'dns-02.ns.aol.com/AAAA/IN': 2001:503:231d::2:30#53
error (network unreachable) resolving 'dns-01.ns.aol.com/A/IN': 2001:503:231d::2:30#53
error (network unreachable) resolving 'dns-01.ns.aol.com/AAAA/IN': 2001:503:231d::2:30#53
error (network unreachable) resolving 'a.service.afiliasdns.info/AAAA/IN': 2a01:8840:6::1#53
error (network unreachable) resolving 'com/DS/IN': 2001:503:ba3e::2:30#53
error (network unreachable) resolving 'a.service.afiliasdns.info/A/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving 'b.service.afiliasdns.org/AAAA/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving 'f.service.afiliasdns.net/A/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving 'f.service.afiliasdns.net/AAAA/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving 'a.service.afiliasdns.info/A/IN': 2a01:8840:8::1#53
error (network unreachable) resolving 'e.service.afiliasdns.info/A/IN': 2001:500:1b::1#53
error (network unreachable) resolving 'org/DNSKEY/IN': 2001:500:f::1#53
error (network unreachable) resolving 'org/DNSKEY/IN': 2001:500:c::1#53
error (network unreachable) resolving 'org/DNSKEY/IN': 2001:500:b::1#53
error (network unreachable) resolving 'org/DNSKEY/IN': 2001:500:48::1#53
error (network unreachable) resolving 'org/DNSKEY/IN': 2001:500:e::1#53
error (network unreachable) resolving 'reddit.com.dlv.isc.org/DLV/IN': 2001:500:71::30#53
error (network unreachable) resolving 'reddit.com.dlv.isc.org/DLV/IN': 2001:500:60::30#53
error (network unreachable) resolving 'org/DNSKEY/IN': 2001:500:40::1#53
error (network unreachable) resolving 'reddit.com.dlv.isc.org/DLV/IN': 2001:4f8:0:2::19#53
error (network unreachable) resolving 'e.service.afiliasdns.info/A/IN': 2a01:8840:7::1#53
error (network unreachable) resolving 'e.service.afiliasdns.info/A/IN': 2001:500:6::79#53
error (network unreachable) resolving 'e.service.afiliasdns.info/A/IN': 2a01:8840:9::1#53
error (network unreachable) resolving 'ns2.isc.ultradns.net/A/IN': 2610:a1:1014::e8#53
error (network unreachable) resolving 'pdns196.ultradns.info/A/IN': 2001:500:1c::1#53
error (network unreachable) resolving 'pdns196.ultradns.info/AAAA/IN': 2001:500:1c::1#53
error (network unreachable) resolving 'pdns196.ultradns.info/A/IN': 2001:500:49::1#53
error (network unreachable) resolving 'pdns196.ultradns.info/AAAA/IN': 2001:500:49::1#53
error (network unreachable) resolving 'pdns196.ultradns.com/A/IN': 2001:502:f3ff::e8#53
error (network unreachable) resolving 'pdns196.ultradns.org/AAAA/IN': 2610:a1:1015::1#53
error (network unreachable) resolving 'pdns196.ultradns.org/A/IN': 2610:a1:1015::1#53
error (network unreachable) resolving 'pdns196.ultradns.info/AAAA/IN': 2610:a1:1016::e8#53
error (network unreachable) resolving 'pdns196.ultradns.info/A/IN': 2610:a1:1016::e8#53
error (network unreachable) resolving 'pdns196.ultradns.biz/A/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving 'pdns6.ultradns.co.uk/A/IN': 2610:a1:1014::1#53
error (network unreachable) resolving 'pdns6.ultradns.co.uk/AAAA/IN': 2610:a1:1014::1#53
error (network unreachable) resolving 'dmoz.org.dlv.isc.org/DLV/IN': 2001:500:2c::254#53
error (network unreachable) resolving 'api.mywot.com/A/IN': 2400:cb00:2049:1::adf5:3b96#53
error (network unreachable) resolving 'clients5.google.com.dlv.isc.org/DLV/IN': 2001:502:ad09::23#53
error (network unreachable) resolving 'google.com.dlv.isc.org/DLV/IN': 2001:500:71::29#53
error (network unreachable) resolving 'pop-ela4-alpha.www.linkedin.com/A/IN': 2001:500:90:1::43#53
error (network unreachable) resolving 'pop-ela4-alpha.www.linkedin.com/A/IN': 2001:500:94:1::43#53
error (network unreachable) resolving 'xml.alexa.com.dlv.isc.org/DLV/IN': 2001:4f8:0:2::20#53
error (network unreachable) resolving 'api.mywot.com.dlv.isc.org/DLV/IN': 2001:4f8:0:2::20#53
error (network unreachable) resolving 'alexa-data-elb-221485408.us-east-1.elb.amazonaws.com.dlv.isc.org/DLV/IN': 2001:500:60::29#53
error (network unreachable) resolving 'alexa-data-elb-221485408.us-east-1.elb.amazonaws.com.dlv.isc.org/DLV/IN': 2001:502:2eda::23#53
error (network unreachable) resolving 'dns02.in-addr.arpa/PTR/IN': 2001:dd8:6::101#53
error (network unreachable) resolving 'in-addr.arpa/DNSKEY/IN': 2001:13c7:7010::53#53
error (network unreachable) resolving 'in-addr.arpa/DS/IN': 2001:500:2f::f#53
error (network unreachable) resolving 'arpa/DNSKEY/IN': 2001:500:1::803f:235#53
error (network unreachable) resolving 'ocsp.ws.symantec.com.edgekey.net/A/IN': 2600:1406:1b::41#53
error (network unreachable) resolving 'net/DS/IN': 2001:7fd::1#53
error (network unreachable) resolving 'net/DNSKEY/IN': 2001:503:a83e::2:30#53
error (network unreachable) resolving 'e8218.ce.akamaiedge.net/A/IN': 2001:503:231d::2:30#53
error (network unreachable) resolving 'centos.mirror.crucial.com.au/AAAA/IN': 2001:dcd:3::5#53
error (network unreachable) resolving 'centos.mirror.crucial.com.au.dlv.isc.org/DLV/IN': 2001:4f8:0:2::19#53
error (network unreachable) resolving 'centos.mirror.crucial.com.au.dlv.isc.org/DLV/IN': 2001:500:60::30#53
error (network unreachable) resolving 'ns2.isc.ultradns.net/A/IN': 2610:a1:1017::e8#53
error (network unreachable) resolving 'ns2.isc.ultradns.net/AAAA/IN': 2610:a1:1017::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2610:a1:1017::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2610:a1:1017::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2001:502:4612::e8#53
error (network unreachable) resolving 'ns2.isc.ultradns.net/A/IN': 2001:502:4612::e8#53
error (network unreachable) resolving 'ns2.isc.ultradns.net/AAAA/IN': 2001:502:4612::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2001:502:4612::e8#53
error (network unreachable) resolving 'au.dlv.isc.org/DLV/IN': 2001:502:ad09::23#53
error (network unreachable) resolving 'au.dlv.isc.org/DLV/IN': 2001:502:2eda::23#53
error (network unreachable) resolving 'org/DNSKEY/IN': 2001:500:c::1#53
error (network unreachable) resolving 'api.ipinfodb.com/A/IN': 2400:cb00:2049:1::adf5:3a93#53
error (network unreachable) resolving 'ns1.msft.net/A/IN': 2a01:111:2020::1:1#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2620:0:32::53#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:200f:1::1:1#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2620:0:37::53#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:2005::1:1#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:2020::1:1#53
received control channel command 'reload'
loading configuration from '/etc/named.conf'
reading built-in trusted keys from file '/etc/named.iscdlv.key'
using default UDP/IPv4 port range: [1024, 65535]
using default UDP/IPv6 port range: [1024, 65535]
sizing zone task pool based on 8 zones
using built-in DLV key for view _default
Warning: 'empty-zones-enable/disable-empty-zone' not set: disabling RFC 1918 empty zones
reloading configuration succeeded
reloading zones succeeded
zone 56.168.192.in-addr.arpa/IN: zone serial (2014080600) unchanged. zone may fail to transfer to slaves.
zone 56.168.192.in-addr.arpa/IN: loaded serial 2014080600
zone mylab.local/IN: zone serial (2014080600) unchanged. zone may fail to transfer to slaves.
zone mylab.local/IN: loaded serial 2014080600
zone 56.168.192.in-addr.arpa/IN: sending notifies (serial 2014080600)
zone mylab.local/IN: sending notifies (serial 2014080600)
received control channel command 'reload mylab.local'
received control channel command 'reload mylab.local IN named.conf'
received control channel command 'reload mylab.local'
received control channel command 'reload mylab.local'
received control channel command 'reload mylab.local'
zone mylab.local/IN: zone serial (2014080600) unchanged. zone may fail to transfer to slaves.
zone mylab.local/IN: loaded serial 2014080600
zone mylab.local/IN: sending notifies (serial 2014080600)
received control channel command 'reload mylab.local'
zone mylab.local/IN: loaded serial 2014080601
zone mylab.local/IN: sending notifies (serial 2014080601)
client 192.168.56.12#48684: transfer of 'mylab.local/IN': AXFR-style IXFR started
client 192.168.56.12#48684: transfer of 'mylab.local/IN': AXFR-style IXFR ended
received control channel command 'reload mylab.local'
zone mylab.local/IN: loaded serial 2014080602
zone mylab.local/IN: sending notifies (serial 2014080602)
client 192.168.56.12#43000: transfer of 'mylab.local/IN': AXFR-style IXFR started
client 192.168.56.12#43000: transfer of 'mylab.local/IN': AXFR-style IXFR ended
received control channel command 'reload mylab.local'
zone mylab.local/IN: loaded serial 2014080603
zone mylab.local/IN: sending notifies (serial 2014080603)
client 192.168.56.12#38635: transfer of 'mylab.local/IN': AXFR-style IXFR started
client 192.168.56.12#38635: transfer of 'mylab.local/IN': AXFR-style IXFR ended
received control channel command 'reload 56.168.192.in-addr.arpa'
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:4f8:0:2::20#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::29#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:60::29#53
error (network unreachable) resolving 'pdns196.ultradns.co.uk/A/IN': 2001:502:4612::1#53
error (network unreachable) resolving 'pdns196.ultradns.co.uk/AAAA/IN': 2001:502:4612::1#53
error (network unreachable) resolving 'pdns196.ultradns.org/A/IN': 2610:a1:1017::1#53
error (network unreachable) resolving 'pdns196.ultradns.org/AAAA/IN': 2610:a1:1017::1#53
error (network unreachable) resolving 'pdns196.ultradns.co.uk/A/IN': 2610:a1:1017::1#53
error (network unreachable) resolving 'pdns196.ultradns.co.uk/AAAA/IN': 2610:a1:1017::1#53
error (network unreachable) resolving 'pdns196.ultradns.org/A/IN': 2610:a1:1015::1#53
error (network unreachable) resolving 'pdns196.ultradns.org/AAAA/IN': 2610:a1:1015::1#53
error (network unreachable) resolving 'pdns196.ultradns.co.uk/A/IN': 2610:a1:1015::1#53
error (network unreachable) resolving 'pdns196.ultradns.co.uk/AAAA/IN': 2610:a1:1015::1#53
received control channel command 'reload 56.168.192.in-addr.arpa'
zone 56.168.192.in-addr.arpa/IN: loaded serial 2014080601
zone 56.168.192.in-addr.arpa/IN: sending notifies (serial 2014080601)
client 192.168.56.12#48835: transfer of '56.168.192.in-addr.arpa/IN': AXFR-style IXFR started
client 192.168.56.12#48835: transfer of '56.168.192.in-addr.arpa/IN': AXFR-style IXFR ended
error (network unreachable) resolving 'progit.org/A/IN': 2001:500:c::1#53
error (unexpected RCODE REFUSED) resolving 'progit.org/A/IN': 69.20.95.4#53
error (unexpected RCODE REFUSED) resolving 'progit.org/A/IN': 65.61.188.4#53
error (unexpected RCODE REFUSED) resolving 'progit.org/A/IN': 69.20.95.4#53
error (unexpected RCODE REFUSED) resolving 'progit.org/A/IN': 65.61.188.4#53
error (unexpected RCODE REFUSED) resolving 'progit.org/A/IN': 69.20.95.4#53
error (unexpected RCODE REFUSED) resolving 'progit.org/A/IN': 65.61.188.4#53
error (unexpected RCODE REFUSED) resolving 'progit.org/A/IN': 69.20.95.4#53
error (unexpected RCODE REFUSED) resolving 'progit.org/A/IN': 65.61.188.4#53
error (unexpected RCODE REFUSED) resolving 'progit.org/A/IN': 69.20.95.4#53
error (unexpected RCODE REFUSED) resolving 'progit.org/A/IN': 65.61.188.4#53
error (network unreachable) resolving 'ipinfodb.com/DS/IN': 2001:503:231d::2:30#53
error (unexpected RCODE REFUSED) resolving 'progit.org/A/IN': 69.20.95.4#53
error (unexpected RCODE REFUSED) resolving 'progit.org/A/IN': 65.61.188.4#53
error (network unreachable) resolving 'github.com.dlv.isc.org/DLV/IN': 2001:500:2c::254#53
error (network unreachable) resolving 'api.ipinfodb.com/A/IN': 2400:cb00:2049:1::adf5:3b94#53
error (network unreachable) resolving 'api.ipinfodb.com/A/IN': 2400:cb00:2049:1::adf5:3a93#53
error (network unreachable) resolving 'collector-cdn.github.com/A/IN': 2001:500:94:1::16#53
error (network unreachable) resolving 'collector.githubapp.com/A/IN': 2001:500:90:1::16#53
error (network unreachable) resolving 'githubapp.com/DS/IN': 2001:503:a83e::2:30#53
error (network unreachable) resolving 'login.live.com/A/IN': 2a01:111:2005::1:1#53
error (network unreachable) resolving 'login.live.com/A/IN': 2a01:111:200f:1::1:1#53
error (network unreachable) resolving 'centos.org/DS/IN': 2001:500:b::1#53
error (network unreachable) resolving 'centos.org/DS/IN': 2001:500:40::1#53
error (network unreachable) resolving 'org/DNSKEY/IN': 2001:500:48::1#53
error (network unreachable) resolving 'mirror.mel.bkb.net.au/A/IN': 2001:dcd:1::5#53
error (network unreachable) resolving 'mirror.mel.bkb.net.au/A/IN': 2001:dcd:3::5#53
error (network unreachable) resolving 'mirror.mel.bkb.net.au/A/IN': 2001:dcd:4::5#53
error (network unreachable) resolving 'mirror.mel.bkb.net.au/A/IN': 2607:f0d0:2002:41::1000:1000#53
error (network unreachable) resolving 'mirror.mel.bkb.net.au/A/IN': 2403:6e00:1000:1000::37:123#53
error (host unreachable) resolving 'mirror.mel.bkb.net.au/A/IN': 27.116.36.47#53
error (network unreachable) resolving 'dlv.ams.sns-pb.isc.org/A/IN': 2001:500:60::30#53
error (network unreachable) resolving 'dlv.ams.sns-pb.isc.org/AAAA/IN': 2001:500:60::30#53
error (network unreachable) resolving 'mirror.mel.bkb.net.au/AAAA/IN': 2403:6e00:1000::47#53
error (network unreachable) resolving '252.30.192.in-addr.arpa/DS/IN': 2001:5a0:10::2#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2610:a1:1017::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2610:a1:1017::e8#53
error (network unreachable) resolving 'pdns196.ultradns.biz/A/IN': 2001:500:3682::12#53
error (network unreachable) resolving 'pdns196.ultradns.biz/AAAA/IN': 2001:500:3682::12#53
error (network unreachable) resolving 'pdns196.ultradns.biz/A/IN': 2001:502:f3ff::e8#53
error (network unreachable) resolving 'pdns196.ultradns.biz/A/IN': 2610:a1:1016::e8#53
error (network unreachable) resolving 'sb.scorecardresearch.com.dlv.isc.org/DLV/IN': 2001:502:2eda::23#53
error (network unreachable) resolving 'sb.scorecardresearch.com.dlv.isc.org/DLV/IN': 2001:502:ad09::23#53
error (network unreachable) resolving 'sb.scorecardresearch.com.edgekey.net/A/IN': 2600:1401:1::41#53
error (network unreachable) resolving './DNSKEY/IN': 2001:500:2f::f#53
error (network unreachable) resolving './NS/IN': 2001:500:2f::f#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:60::30#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::30#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:4f8:0:2::19#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:2c::254#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2001:502:f3ff::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2001:502:f3ff::e8#53
error (network unreachable) resolving 'ns2.isc.ultradns.net/A/IN': 2610:a1:1014::e8#53
error (network unreachable) resolving 'ns2.isc.ultradns.net/AAAA/IN': 2610:a1:1014::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2610:a1:1014::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2610:a1:1014::e8#53
error (network unreachable) resolving 'ns2.isc.ultradns.net/A/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving 'ns2.isc.ultradns.net/AAAA/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2001:502:4612::e8#53
error (network unreachable) resolving 'ns2.isc.ultradns.net/A/IN': 2001:502:4612::e8#53
error (network unreachable) resolving 'ns2.isc.ultradns.net/AAAA/IN': 2001:502:4612::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2001:502:4612::e8#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::30#53
error (network unreachable) resolving 'mail.live.com/A/IN': 2620:0:32::53#53
error (network unreachable) resolving 'mail.live.com/A/IN': 2620:0:37::53#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:2bad::17#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:2002::17#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com.dlv.isc.org/DLV/IN': 2001:500:60::29#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com.dlv.isc.org/DLV/IN': 2001:4f8:0:2::20#53
error (network unreachable) resolving 'microsoft.com/DS/IN': 2001:503:231d::2:30#53
error (network unreachable) resolving './DNSKEY/IN': 2001:dc3::35#53
error (network unreachable) resolving './NS/IN': 2001:dc3::35#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::30#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::29#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::29#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:4f8:0:2::20#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2001:502:f3ff::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2001:502:f3ff::e8#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:60::29#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2620:0:37::53#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:200f:1::1:1#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2620:0:32::53#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:2002::17#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:2bad::17#53
error (network unreachable) resolving 'www.evernote.com/A/IN': 2001:503:a83e::2:30#53
error (network unreachable) resolving 'www.evernote.com/A/IN': 2600:1800:5::1#53
error (network unreachable) resolving 'ns1.p21.dynect.net/A/IN': 2001:500:94::100#53
error (network unreachable) resolving 'ns1.p21.dynect.net/AAAA/IN': 2001:500:94::100#53
error (network unreachable) resolving 'ns2.p21.dynect.net/A/IN': 2001:500:90::100#53
error (network unreachable) resolving 'ns2.p21.dynect.net/AAAA/IN': 2001:500:90::100#53
error (network unreachable) resolving 'ns1.p21.dynect.net/A/IN': 2001:500:90::100#53
error (network unreachable) resolving 'ns1.p21.dynect.net/AAAA/IN': 2001:500:90::100#53
error (network unreachable) resolving './DNSKEY/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving './NS/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::30#53
error (network unreachable) resolving './DNSKEY/IN': 2001:500:1::803f:235#53
error (network unreachable) resolving './NS/IN': 2001:500:1::803f:235#53
error (network unreachable) resolving 'mail.live.com/A/IN': 2a01:111:200f:1::1:1#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2610:a1:1016::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2610:a1:1016::e8#53
error (network unreachable) resolving 'ns2.isc.ultradns.net/A/IN': 2001:502:f3ff::e8#53
error (network unreachable) resolving 'ns2.isc.ultradns.net/AAAA/IN': 2001:502:f3ff::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2001:502:f3ff::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2001:502:f3ff::e8#53
error (network unreachable) resolving 'ns2.isc.ultradns.net/A/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving 'ns2.isc.ultradns.net/AAAA/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2620:0:32::53#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:2bad::17#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:2002::17#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com.dlv.isc.org/DLV/IN': 2001:502:ad09::23#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com.dlv.isc.org/DLV/IN': 2001:502:2eda::23#53
error (network unreachable) resolving 'pdns196.ultradns.biz/A/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2620:0:37::53#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2620:0:32::53#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:200f:1::1:1#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:2002::17#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:2bad::17#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com.dlv.isc.org/DLV/IN': 2001:502:ad09::23#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com.dlv.isc.org/DLV/IN': 2001:502:2eda::23#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:60::30#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::30#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:4f8:0:2::19#53
error (network unreachable) resolving 'www.evernote.com/A/IN': 2600:1800:5::1#53
error (network unreachable) resolving 'mail.live.com/A/IN': 2620:0:32::53#53
error (network unreachable) resolving 'mail.live.com.dlv.isc.org/DLV/IN': 2001:500:60::29#53
error (network unreachable) resolving 'mail.live.com.dlv.isc.org/DLV/IN': 2001:4f8:0:2::20#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2001:502:f3ff::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2001:502:f3ff::e8#53
error (network unreachable) resolving 'mail.live.com.dlv.isc.org/DLV/IN': 2001:500:71::29#53
error (network unreachable) resolving 'mail.live.com.dlv.isc.org/DLV/IN': 2001:500:2c::254#53
error (network unreachable) resolving 'ocsp.ws.symantec.com.edgekey.net.dlv.isc.org/DLV/IN': 2001:502:ad09::23#53
error (network unreachable) resolving 'ocsp.ws.symantec.com.edgekey.net.dlv.isc.org/DLV/IN': 2001:502:2eda::23#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:2bad::17#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:2002::17#53
error (network unreachable) resolving 'mail.live.com/A/IN': 2a01:111:2020::1:1#53
error (network unreachable) resolving 'mail.live.com/A/IN': 2a01:111:2005::1:1#53
error (network unreachable) resolving 'mail.live.com.dlv.isc.org/DLV/IN': 2001:500:60::30#53
error (network unreachable) resolving 'mail.live.com.dlv.isc.org/DLV/IN': 2001:500:71::30#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2610:a1:1016::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2610:a1:1016::e8#53
error (network unreachable) resolving 'pdns196.ultradns.biz/A/IN': 2001:503:7bbb:ffff:ffff:ffff:ffff:ff7e#53
error (network unreachable) resolving 'pdns196.ultradns.biz/AAAA/IN': 2001:503:7bbb:ffff:ffff:ffff:ffff:ff7e#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:200f:1::1:1#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2620:0:32::53#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2620:0:37::53#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com.dlv.isc.org/DLV/IN': 2001:502:ad09::23#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2610:a1:1016::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2610:a1:1016::e8#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2620:0:37::53#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:60::30#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::29#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:4f8:0:2::20#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2610:a1:1016::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2610:a1:1016::e8#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:2005::1:1#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:2020::1:1#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2620:0:32::53#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2620:0:37::53#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:200f:1::1:1#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:2bad::17#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:2002::17#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::30#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:4f8:0:2::19#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:4f8:0:2::20#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:60::29#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::29#53
error (network unreachable) resolving 'mail.live.com/A/IN': 2620:0:37::53#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2620:0:32::53#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:200f:1::1:1#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:2005::1:1#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:2020::1:1#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:2002::17#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:60::30#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:60::29#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::29#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:4f8:0:2::20#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:2c::254#53
error (network unreachable) resolving 'pdns196.ultradns.biz/A/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving 'mail.live.com.dlv.isc.org/DLV/IN': 2001:500:60::29#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2620:0:37::53#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:4f8:0:2::20#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::29#53
error (network unreachable) resolving './DNSKEY/IN': 2001:500:1::803f:235#53
error (network unreachable) resolving './NS/IN': 2001:500:1::803f:235#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:4f8:0:2::19#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::30#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:60::30#53
error (network unreachable) resolving 'www.prweek.com/A/IN': 2001:503:231d::2:30#53
error (network unreachable) resolving 'pdns2.cscdns.net/A/IN': 2620:74:19::33#53
error (network unreachable) resolving 'pdns2.cscdns.net/A/IN': 2001:502:cbe4::33#53
error (network unreachable) resolving 'git.or.cz/A/IN': 2001:678:f::1#53
error (network unreachable) resolving 'git.or.cz/A/IN': 2001:678:11::1#53
error (network unreachable) resolving 'speakerrate.com/A/IN': 2620:111:8002::53#53
error (network unreachable) resolving 'or.cz/DS/IN': 2001:678:1::1#53
error (network unreachable) resolving 'or.cz/DS/IN': 2001:678:10::1#53
error (network unreachable) resolving 'git.or.cz.dlv.isc.org/DLV/IN': 2001:500:60::29#53
error (network unreachable) resolving 'git.or.cz.dlv.isc.org/DLV/IN': 2001:500:71::29#53
error (network unreachable) resolving 'git.or.cz.dlv.isc.org/DLV/IN': 2001:4f8:0:2::20#53
error (network unreachable) resolving 'repo.or.cz/A/IN': 2001:470:6f:a8::1#53
error (network unreachable) resolving 'ns1.no-ip.com/A/IN': 2001:503:a83e::2:30#53
error (network unreachable) resolving 'ns1.no-ip.com/AAAA/IN': 2001:503:a83e::2:30#53
error (network unreachable) resolving 'ns0.ja.net/A/IN': 2001:630:0:44::e2#53
error (network unreachable) resolving 'ns0.ja.net/AAAA/IN': 2001:630:0:44::e2#53
error (network unreachable) resolving 'ns1.zurich.surf.net/AAAA/IN': 2001:630:0:9::14#53
error (network unreachable) resolving 'ns0.ja.net/A/IN': 2001:630:0:47::42#53
error (network unreachable) resolving 'ns0.ja.net/AAAA/IN': 2001:630:0:47::42#53
error (network unreachable) resolving 'ns0.ja.net/A/IN': 2001:630:0:9::14#53
error (network unreachable) resolving 'ns0.ja.net/AAAA/IN': 2001:630:0:9::14#53
error (network unreachable) resolving 'ns-1298.awsdns-34.org/A/IN': 2001:500:c::1#53
error (network unreachable) resolving 'ns-1298.awsdns-34.org/AAAA/IN': 2001:500:c::1#53
error (network unreachable) resolving 'ns-1698.awsdns-20.co.uk/A/IN': 2001:630:181:35::83#53
error (network unreachable) resolving 'ns-1698.awsdns-20.co.uk/AAAA/IN': 2001:630:181:35::83#53
error (network unreachable) resolving 'ns-1298.awsdns-34.org/A/IN': 2001:500:48::1#53
error (network unreachable) resolving 'ns-1298.awsdns-34.org/AAAA/IN': 2001:500:48::1#53
error (network unreachable) resolving 'ns-1698.awsdns-20.co.uk/A/IN': 2a01:40:1001:35::2#53
error (network unreachable) resolving 'ns-1698.awsdns-20.co.uk/AAAA/IN': 2a01:40:1001:35::2#53
error (network unreachable) resolving 'ns-1298.awsdns-34.org/A/IN': 2001:500:f::1#53
error (network unreachable) resolving 'ns-1298.awsdns-34.org/AAAA/IN': 2001:500:f::1#53
error (network unreachable) resolving 'ip-address/A/IN': 2001:dc3::35#53
error (network unreachable) resolving 'ns9.hostgator.in/A/IN': 2001:500:2f::f#53
error (network unreachable) resolving 'ns9.hostgator.in/AAAA/IN': 2001:500:2f::f#53
error (network unreachable) resolving 'www.tuxmachines.org/A/IN': 2001:500:b::1#53
error (network unreachable) resolving 'ns9.hostgator.in/A/IN': 2001:678:4::7#53
error (network unreachable) resolving 'ns9.hostgator.in/AAAA/IN': 2001:678:4::7#53
error (network unreachable) resolving 'ns1.p13.dynect.net/A/IN': 2001:500:90::100#53
error (network unreachable) resolving 'ns1.p13.dynect.net/AAAA/IN': 2001:500:90::100#53
error (network unreachable) resolving 'ns1.p13.dynect.net/A/IN': 2001:500:94::100#53
error (network unreachable) resolving 'ns1.p13.dynect.net/AAAA/IN': 2001:500:94::100#53
error (network unreachable) resolving 'centos.org/DS/IN': 2001:500:e::1#53
error (network unreachable) resolving 'centos.org/DS/IN': 2001:500:40::1#53
error (network unreachable) resolving 'mirror.mel.bkb.net.au/A/IN': 2403:6e00:1000:1000::37:122#53
error (network unreachable) resolving 'au/DS/IN': 2001:503:ba3e::2:30#53
error (network unreachable) resolving 'au/DS/IN': 2001:500:1::803f:235#53
error (network unreachable) resolving 'centos.mirror.uber.com.au/A/IN': 2001:dc0:4001:1:0:1836:0:141#53
error (network unreachable) resolving 'ns1.udns.net.au/A/IN': 2001:dcd:2::5#53
error (network unreachable) resolving 'ns1.udns.net.au/AAAA/IN': 2001:dcd:2::5#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::30#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2001:502:f3ff::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2001:502:f3ff::e8#53
error (network unreachable) resolving 'ns.icann.org/AAAA/IN': 2001:500:89::53#53
error (network unreachable) resolving 'internic.net.dlv.isc.org/DLV/IN': 2001:502:2eda::23#53
error (network unreachable) resolving 'internic.net.dlv.isc.org/DLV/IN': 2001:502:ad09::23#53
validating @0xb45ef050: www.internic.net A: no valid signature found
error (network unreachable) resolving 'internicwww.vip.icann.org/A/IN': 2001:500:8c::53#53
error (network unreachable) resolving 'internicwww.vip.icann.org/A/IN': 2001:500:8e::53#53
error (network unreachable) resolving 'internicwww.vip.icann.org/A/IN': 2001:500:8d::53#53
error (network unreachable) resolving 'icann.org/DS/IN': 2001:500:48::1#53
error (network unreachable) resolving 'icann.org/DS/IN': 2001:500:40::1#53
error (network unreachable) resolving 'icann.org/DS/IN': 2001:500:f::1#53
error (network unreachable) resolving 'tigris.org/DS/IN': 2001:500:b::1#53
error (network unreachable) resolving 'org/DNSKEY/IN': 2001:500:e::1#53
error (network unreachable) resolving 'org/DNSKEY/IN': 2001:500:c::1#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:2002::17#53
error (network unreachable) resolving './DNSKEY/IN': 2001:7fd::1#53
error (network unreachable) resolving './NS/IN': 2001:7fd::1#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:60::30#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:4f8:0:2::19#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::30#53
error (network unreachable) resolving 'pdns196.ultradns.biz/A/IN': 2001:500:3682::12#53
error (network unreachable) resolving 'pdns196.ultradns.biz/AAAA/IN': 2001:500:3682::12#53
error (network unreachable) resolving 'pdns196.ultradns.biz/A/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving 'pdns196.ultradns.biz/AAAA/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving 'skypewebexperience.live.com/A/IN': 2a01:111:2020::1:1#53
error (network unreachable) resolving 'skypewebexperience.trafficmanager.net.dlv.isc.org/DLV/IN': 2001:502:ad09::23#53
error (network unreachable) resolving 'skypewebexperience.trafficmanager.net.dlv.isc.org/DLV/IN': 2001:502:2eda::23#53
error (network unreachable) resolving 'swxeus03.cloudapp.net/A/IN': 2a01:111:2020:3::5#53
received control channel command 'reload mylab.local'
zone mylab.local/IN: zone serial (2014080603) unchanged. zone may fail to transfer to slaves.
zone mylab.local/IN: loaded serial 2014080603
zone mylab.local/IN: sending notifies (serial 2014080603)
received control channel command 'reload mylab.local'
zone mylab.local/IN: loaded serial 2014080700
zone mylab.local/IN: sending notifies (serial 2014080700)
client 192.168.56.12#32768: transfer of 'mylab.local/IN': AXFR-style IXFR started
client 192.168.56.12#32768: transfer of 'mylab.local/IN': AXFR-style IXFR ended
error (network unreachable) resolving 'org/DNSKEY/IN': 2001:500:b::1#53
error (network unreachable) resolving 'org/DNSKEY/IN': 2001:500:f::1#53
error (network unreachable) resolving 'subversion.tigris.org.dlv.isc.org/DLV/IN': 2001:4f8:0:2::20#53
error (network unreachable) resolving 'microsoft.com/DS/IN': 2001:503:231d::2:30#53
error (network unreachable) resolving 'ns.tokkee.org/A/IN': 2001:500:c::1#53
error (network unreachable) resolving 'ns.tokkee.org/AAAA/IN': 2001:500:c::1#53
error (network unreachable) resolving 'ipv4.casella.faui2k3.org/A/IN': 2001:500:48::1#53
error (network unreachable) resolving 'ipv4.casella.faui2k3.org/AAAA/IN': 2001:500:48::1#53
error (network unreachable) resolving 'ns.tokkee.org/A/IN': 2001:500:48::1#53
error (network unreachable) resolving 'ns.tokkee.org/AAAA/IN': 2001:500:48::1#53
error (network unreachable) resolving 'dns1.noris.net/AAAA/IN': 2001:780:53d1::53#53
error (network unreachable) resolving 'nsa.domain-robot.org/A/IN': 2001:500:e::1#53
error (network unreachable) resolving 'nsa.domain-robot.org/AAAA/IN': 2001:500:e::1#53
error (network unreachable) resolving 'google.com/DS/IN': 2001:503:a83e::2:30#53
error (network unreachable) resolving 'powerdns.com/DNSKEY/IN': 2a01:4f8:110:4389::2#53
error (network unreachable) resolving 'ipv4.casella.faui2k3.org/AAAA/IN': 2001:500:e::1#53
error (network unreachable) resolving 'www.google.com.dlv.isc.org/DLV/IN': 2001:500:71::29#53
error (network unreachable) resolving 'google.com.dlv.isc.org/DLV/IN': 2001:500:60::29#53
error (network unreachable) resolving 'dns.noris.ch/A/IN': 2001:780:53d2::53#53
error (network unreachable) resolving 'dns.noris.ch/A/IN': 2001:780:53d3::53#53
error (network unreachable) resolving 'dns.noris.ch/A/IN': 2001:780:53d1::53#53
error (network unreachable) resolving 'perlgeek.de/DS/IN': 2001:668:1f:11::105#53
error (network unreachable) resolving 'perlgeek.de/DS/IN': 2001:678:2::53#53
error (network unreachable) resolving 'perlgeek.de/DS/IN': 2001:67c:1011:1::53#53
error (network unreachable) resolving 'xs.powerdns.com/A/IN': 2001:888:2000:1d::2#53
error (network unreachable) resolving 'www.freebsd.org/A/IN': 2001:500:40::1#53
error (network unreachable) resolving 'www.freebsd.org/A/IN': 2001:5a0:10::1#53
error (network unreachable) resolving 'www.freebsd.org/A/IN': 2001:470:1a::1#53
error (network unreachable) resolving 'ext.squarespace.com/A/IN': 2001:500:94:1::6#53
error (network unreachable) resolving 'ext.squarespace.com/A/IN': 2001:500:90:1::6#53
error (network unreachable) resolving 'api.ipinfodb.com/A/IN': 2400:cb00:2049:1::adf5:3b94#53
error (network unreachable) resolving 'cdn.api.twitter.com/A/IN': 2001:500:90:1::34#53
error (network unreachable) resolving 'cdn.api.twitter.com/A/IN': 2001:500:94:1::34#53
error (network unreachable) resolving 'a1168.dsw4.akamai.net/A/IN': 2001:559:0:3f0:902b:c139:647c:9b31#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:2020::1:1#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com/A/IN': 2a01:111:2002::17#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:2c::254#53
error (network unreachable) resolving 'au.dlv.isc.org/DLV/IN': 2001:4f8:0:2::20#53
error (network unreachable) resolving 'google.com/DS/IN': 2001:503:231d::2:30#53
error (network unreachable) resolving 'jafdip.com/A/IN': 2400:cb00:2049:1::adf5:3a78#53
error (network unreachable) resolving 'jafdip.com/A/IN': 2400:cb00:2049:1::adf5:3b7b#53
error (network unreachable) resolving 'cs107.wac.edgecastcdn.net/A/IN': 2606:2800:1::5#53
error (network unreachable) resolving 'cs107.wac.edgecastcdn.net/A/IN': 2606:2800:1::6#53
error (network unreachable) resolving 'api.ipinfodb.com/A/IN': 2400:cb00:2049:1::adf5:3a93#53
error (network unreachable) resolving 'squarespace.com/DS/IN': 2001:503:a83e::2:30#53
error (network unreachable) resolving 'en.wikipedia.org.dlv.isc.org/DLV/IN': 2001:500:71::30#53
error (network unreachable) resolving 'en.wikipedia.org.dlv.isc.org/DLV/IN': 2001:4f8:0:2::19#53
error (network unreachable) resolving 'p01.t.eloqua.com/A/IN': 2001:500:7967::2:33#53
error (network unreachable) resolving 'www.ofazomi.org.dlv.isc.org/DLV/IN': 2001:502:ad09::23#53
error (network unreachable) resolving 'www.ofazomi.org.dlv.isc.org/DLV/IN': 2001:502:2eda::23#53
error (network unreachable) resolving 'www.ofazomi.org.dlv.isc.org/DLV/IN': 2001:500:71::29#53
error (network unreachable) resolving 'www.ofazomi.org.dlv.isc.org/DLV/IN': 2001:500:60::29#53
error (network unreachable) resolving './DNSKEY/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving './NS/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving 'tigris.org/DS/IN': 2001:500:40::1#53
error (network unreachable) resolving 'org/DNSKEY/IN': 2001:500:f::1#53
error (network unreachable) resolving 'subversion.tigris.org.dlv.isc.org/DLV/IN': 2001:500:71::30#53
error (network unreachable) resolving 'subversion.tigris.org.dlv.isc.org/DLV/IN': 2001:500:60::30#53
error (network unreachable) resolving 'subversion.tigris.org.dlv.isc.org/DLV/IN': 2001:4f8:0:2::19#53
error (network unreachable) resolving 'pns3.cloudns.net/AAAA/IN': 2401:c900:1101:de::2#53
error (network unreachable) resolving 'prchecker.info/DS/IN': 2001:500:19::1#53
error (network unreachable) resolving './DNSKEY/IN': 2001:503:ba3e::2:30#53
error (network unreachable) resolving './NS/IN': 2001:503:ba3e::2:30#53
error (network unreachable) resolving './DNSKEY/IN': 2001:dc3::35#53
error (network unreachable) resolving './NS/IN': 2001:dc3::35#53
error (network unreachable) resolving 'mail.live.com/A/IN': 2620:0:37::53#53
error (network unreachable) resolving 'mail.live.com/A/IN': 2a01:111:200f:1::1:1#53
error (network unreachable) resolving 'mail.live.com.dlv.isc.org/DLV/IN': 2001:500:b::1#53
error (network unreachable) resolving 'mail.live.com.dlv.isc.org/DLV/IN': 2001:500:c::1#53
error (network unreachable) resolving 'mail.live.com.dlv.isc.org/DLV/IN': 2001:500:48::1#53
error (network unreachable) resolving 'mail.live.com.dlv.isc.org/DLV/IN': 2001:500:71::30#53
error (network unreachable) resolving 'ns.isc.afilias-nst.info/A/IN': 2001:500:1b::1#53
error (network unreachable) resolving 'ns.isc.afilias-nst.info/AAAA/IN': 2001:500:1b::1#53
error (network unreachable) resolving 'mail.live.com.dlv.isc.org/DLV/IN': 2001:4f8:0:2::20#53
error (network unreachable) resolving 'pdns196.ultradns.co.uk/A/IN': 2610:a1:1017::1#53
error (network unreachable) resolving 'pdns196.ultradns.co.uk/AAAA/IN': 2610:a1:1017::1#53
error (network unreachable) resolving 'pdns196.ultradns.info/A/IN': 2001:500:1a::1#53
error (network unreachable) resolving 'pdns196.ultradns.info/AAAA/IN': 2001:500:1a::1#53
error (network unreachable) resolving 'pdns196.ultradns.info/A/IN': 2610:a1:1016::e8#53
error (network unreachable) resolving 'pdns5.ultradns.info/AAAA/IN': 2001:502:f3ff::e8#53
error (network unreachable) resolving 'pdns5.ultradns.info/AAAA/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving './DNSKEY/IN': 2001:503:ba3e::2:30#53
error (network unreachable) resolving './NS/IN': 2001:503:ba3e::2:30#53
error (network unreachable) resolving 'svnbook.red-bean.com.dlv.isc.org/DLV/IN': 2001:500:71::29#53
error (network unreachable) resolving 'svnbook.red-bean.com.dlv.isc.org/DLV/IN': 2001:500:60::29#53
error (network unreachable) resolving 'svnbook.red-bean.com.dlv.isc.org/DLV/IN': 2001:500:2c::254#53
error (network unreachable) resolving 'mail.live.com/A/IN': 2620:0:37::53#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2001:502:4612::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2001:502:4612::e8#53
error (network unreachable) resolving 'pdns196.ultradns.biz/AAAA/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving 'dispatch.kahuna.glbdns2.microsoft.com.dlv.isc.org/DLV/IN': 2001:502:2eda::23#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::30#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:4f8:0:2::19#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:60::30#53
error (network unreachable) resolving 'pdns196.ultradns.biz/A/IN': 2001:503:7bbb:ffff:ffff:ffff:ffff:ff7e#53
error (network unreachable) resolving 'pdns196.ultradns.biz/AAAA/IN': 2001:503:7bbb:ffff:ffff:ffff:ffff:ff7e#53
error (network unreachable) resolving './DNSKEY/IN': 2001:dc3::35#53
error (network unreachable) resolving './NS/IN': 2001:dc3::35#53
error (network unreachable) resolving './DNSKEY/IN': 2001:500:1::803f:235#53
error (network unreachable) resolving './NS/IN': 2001:500:1::803f:235#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:4f8:0:2::20#53
error (network unreachable) resolving './DNSKEY/IN': 2001:500:2f::f#53
error (network unreachable) resolving './NS/IN': 2001:500:2f::f#53
error (network unreachable) resolving './DNSKEY/IN': 2001:7fd::1#53
error (network unreachable) resolving './NS/IN': 2001:7fd::1#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:4f8:0:2::20#53
error (network unreachable) resolving 'pdns196.ultradns.biz/A/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving 'pdns196.ultradns.biz/AAAA/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving './DNSKEY/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving './NS/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::29#53
error (network unreachable) resolving './DNSKEY/IN': 2001:500:2f::f#53
error (network unreachable) resolving './NS/IN': 2001:500:2f::f#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:60::29#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:4f8:0:2::20#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2001:502:f3ff::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2001:502:f3ff::e8#53
error (network unreachable) resolving 'ns2.isc.ultradns.net/A/IN': 2610:a1:1017::e8#53
error (network unreachable) resolving 'ns2.isc.ultradns.net/AAAA/IN': 2610:a1:1017::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2610:a1:1017::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2610:a1:1017::e8#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:60::30#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::30#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:4f8:0:2::19#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2610:a1:1014::e8#53
error (network unreachable) resolving 'ns2.isc.ultradns.net/A/IN': 2610:a1:1014::e8#53
error (network unreachable) resolving 'ns2.isc.ultradns.net/AAAA/IN': 2610:a1:1014::e8#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:60::29#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:4f8:0:2::19#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2001:502:f3ff::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2001:502:f3ff::e8#53
error (network unreachable) resolving 'pdns196.ultradns.biz/A/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving 'pdns196.ultradns.biz/AAAA/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:4f8:0:2::19#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::30#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:60::30#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:2c::254#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:4f8:0:2::19#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:60::30#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::30#53
error (network unreachable) resolving './DNSKEY/IN': 2001:503:ba3e::2:30#53
error (network unreachable) resolving './NS/IN': 2001:503:ba3e::2:30#53
error (network unreachable) resolving './DNSKEY/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving './NS/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving 'pdns196.ultradns.biz/A/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving 'pdns196.ultradns.biz/AAAA/IN': 2610:a1:1015::e8#53
error (network unreachable) resolving './DNSKEY/IN': 2001:500:1::803f:235#53
error (network unreachable) resolving './NS/IN': 2001:500:1::803f:235#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/A/IN': 2001:502:f3ff::e8#53
error (network unreachable) resolving 'ns1.isc.ultradns.net/AAAA/IN': 2001:502:f3ff::e8#53
error (network unreachable) resolving './DNSKEY/IN': 2001:dc3::35#53
error (network unreachable) resolving './NS/IN': 2001:dc3::35#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::29#53
error (network unreachable) resolving './DNSKEY/IN': 2001:500:2f::f#53
error (network unreachable) resolving './NS/IN': 2001:500:2f::f#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:60::30#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::30#53
error (network unreachable) resolving './DNSKEY/IN': 2001:500:1::803f:235#53
error (network unreachable) resolving './NS/IN': 2001:500:1::803f:235#53
error (network unreachable) resolving 'dlv.isc.org/DNSKEY/IN': 2001:500:71::30#53
error (network unreachable) resolving 'pdns196.ultradns.biz/A/IN': 2610:a1:1015::e8#53
